import XCTest
import Contacts
@testable import CaucoHostCore

final class HostCoreTests: XCTestCase {
    private var temporary: [URL] = []
    override func tearDown() { temporary.forEach { try? FileManager.default.removeItem(at: $0) }; temporary.removeAll() }
    private func repository(valid: Bool = true, executable: Bool = true) throws -> URL {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString); temporary.append(root)
        let fm = FileManager.default; try fm.createDirectory(at: root.appendingPathComponent("core"), withIntermediateDirectories: true); try fm.createDirectory(at: root.appendingPathComponent(".venv/bin"), withIntermediateDirectories: true)
        if valid { fm.createFile(atPath: root.appendingPathComponent("core/pyproject.toml").path, contents: Data()) }
        if executable { fm.createFile(atPath: root.appendingPathComponent(".venv/bin/python").path, contents: Data()); try fm.setAttributes([.posixPermissions: 0o700], ofItemAtPath: root.appendingPathComponent(".venv/bin/python").path) }
        return root
    }
    func testAuthorizationMapping() { XCTAssertEqual(NativeContactsPermissionGateway.map(.notDetermined), .notRequested); XCTAssertEqual(NativeContactsPermissionGateway.map(.denied), .denied); XCTAssertEqual(NativeContactsPermissionGateway.map(.restricted), .restricted) }
    func testNoConfiguredRepository() { let d = UserDefaults(suiteName: UUID().uuidString)!; XCTAssertThrowsError(try RepositoryConfiguration.resolve(userDefaults: d, environment: [:], workingDirectory: URL(fileURLWithPath: "/Applications/Cauco.app"))) { XCTAssertEqual($0 as? RepositoryResolutionError, .unconfigured) } }
    func testFilesystemRootRejected() { XCTAssertThrowsError(try RepositoryConfiguration.validate(URL(fileURLWithPath: "/"))) { XCTAssertEqual($0 as? RepositoryResolutionError, .rootRejected) } }
    func testValidRepositoryAndExecutablePath() throws { let root = try repository(); let result = try RepositoryConfiguration.validate(root); XCTAssertEqual(result.repository, root.standardizedFileURL); XCTAssertEqual(result.executable, root.standardizedFileURL.appendingPathComponent(".venv/bin/python")) }
    func testRegularExecutableAccepted() throws { XCTAssertNoThrow(try RepositoryConfiguration.validate(try repository())) }
    func testValidSymlinkToExecutableAcceptedButLogicalEntrypointLaunched() throws { let root = try repository(executable: false); let outside = root.deletingLastPathComponent().appendingPathComponent(UUID().uuidString); temporary.append(outside); FileManager.default.createFile(atPath: outside.path, contents: Data()); try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: outside.path); let logical = root.appendingPathComponent(".venv/bin/python"); try FileManager.default.createSymbolicLink(at: logical, withDestinationURL: outside); let result = try RepositoryConfiguration.validate(root); XCTAssertEqual(result.executable, logical.standardizedFileURL) }
    func testBrokenSymlinkRejected() throws { let root = try repository(executable: false); let logical = root.appendingPathComponent(".venv/bin/python"); try FileManager.default.createSymbolicLink(at: logical, withDestinationURL: root.appendingPathComponent("missing-python")); XCTAssertThrowsError(try RepositoryConfiguration.validate(root)) { XCTAssertEqual($0 as? RepositoryResolutionError, .missingPython(logical)) } }
    func testSymlinkToDirectoryRejected() throws { let root = try repository(executable: false); let destination = root.appendingPathComponent("python-directory"); try FileManager.default.createDirectory(at: destination, withIntermediateDirectories: false); let logical = root.appendingPathComponent(".venv/bin/python"); try FileManager.default.createSymbolicLink(at: logical, withDestinationURL: destination); XCTAssertThrowsError(try RepositoryConfiguration.validate(root)) { XCTAssertEqual($0 as? RepositoryResolutionError, .pythonNotRegular(logical)) } }
    func testSymlinkToNonExecutableFileRejected() throws { let root = try repository(executable: false); let destination = root.appendingPathComponent("python-file"); FileManager.default.createFile(atPath: destination.path, contents: Data()); try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: destination.path); let logical = root.appendingPathComponent(".venv/bin/python"); try FileManager.default.createSymbolicLink(at: logical, withDestinationURL: destination); XCTAssertThrowsError(try RepositoryConfiguration.validate(root)) { XCTAssertEqual($0 as? RepositoryResolutionError, .pythonNotExecutable(logical)) } }
    func testMissingManifestRejected() throws { let root = try repository(valid: false); XCTAssertThrowsError(try RepositoryConfiguration.validate(root)) { XCTAssertEqual($0 as? RepositoryResolutionError, .missingCoreManifest(root.appendingPathComponent("core/pyproject.toml"))) } }
    func testMissingPythonRejected() throws { let root = try repository(executable: false); XCTAssertThrowsError(try RepositoryConfiguration.validate(root)) { XCTAssertEqual($0 as? RepositoryResolutionError, .missingPython(root.appendingPathComponent(".venv/bin/python"))) } }
    func testNonExecutablePythonRejected() throws { let root = try repository(); let python = root.appendingPathComponent(".venv/bin/python"); try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: python.path); XCTAssertThrowsError(try RepositoryConfiguration.validate(root)) { XCTAssertEqual($0 as? RepositoryResolutionError, .pythonNotExecutable(python)) } }
    func testUserDefaultsPrecedesEnvironmentAndSourceIsDisplayedData() throws { let selected = try repository(); let env = try repository(); let d = UserDefaults(suiteName: UUID().uuidString)!; d.set(selected.path, forKey: repositoryPathDefaultsKey); let result = try RepositoryConfiguration.resolve(userDefaults: d, environment: [repositoryPathEnvironmentKey: env.path], workingDirectory: URL(fileURLWithPath: "/Applications/Cauco.app")); XCTAssertEqual(result.repository, selected.standardizedFileURL); XCTAssertEqual(result.source, .configured); XCTAssertFalse("Not configured" == "\(result.source.rawValue): \(result.repository.path)") }
    func testEnvironmentFallbackAndSource() throws { let root = try repository(); let d = UserDefaults(suiteName: UUID().uuidString)!; let result = try RepositoryConfiguration.resolve(userDefaults: d, environment: [repositoryPathEnvironmentKey: root.path], workingDirectory: URL(fileURLWithPath: "/Applications/Cauco.app")); XCTAssertEqual(result.repository, root.standardizedFileURL); XCTAssertEqual(result.source, .environment) }
    func testInstalledAppDoesNotProduceFilesystemRoot() { XCTAssertThrowsError(try RepositoryConfiguration.resolve(userDefaults: UserDefaults(suiteName: UUID().uuidString)!, environment: [:], workingDirectory: URL(fileURLWithPath: "/Applications/Cauco.app"))) { XCTAssertFalse(($0 as? RepositoryResolutionError) == .rootRejected) } }
    func testRepositoryBuildTreeFallbackIsNotUnconfigured() throws { let root = try repository(); let result = try RepositoryConfiguration.resolve(userDefaults: UserDefaults(suiteName: UUID().uuidString)!, environment: [:], workingDirectory: root); XCTAssertEqual(result.repository, root.standardizedFileURL); XCTAssertEqual(result.source, .developmentFallback) }
    func testFixedArgumentsRemainUnchanged() { let c = CoreLaunchConfiguration(executable: URL(fileURLWithPath: "/tmp/python"), repository: URL(fileURLWithPath: "/tmp/repo")); XCTAssertEqual(c.arguments, ["-m", "uvicorn", "cauco_core.main:app", "--host", "127.0.0.1", "--port", "8765"]); XCTAssertTrue(isLocalCoreURL(c.url)); XCTAssertFalse(c.arguments.contains(where: { $0.contains(";") })) }
    func testSelectionDoesNotStartCoreAndClearingIsUnconfigured() throws { let root = try repository(); let d = UserDefaults(suiteName: UUID().uuidString)!; d.set(root.path, forKey: repositoryPathDefaultsKey); XCTAssertNotNil(d.string(forKey: repositoryPathDefaultsKey)); d.removeObject(forKey: repositoryPathDefaultsKey); XCTAssertNil(d.string(forKey: repositoryPathDefaultsKey)); XCTAssertThrowsError(try RepositoryConfiguration.resolve(userDefaults: d, environment: [:], workingDirectory: URL(fileURLWithPath: "/Applications/Cauco.app"))) }
    func testArbitraryExecutablePathCannotBeSupplied() throws { let root = try repository(); let arbitrary = root.appendingPathComponent("arbitrary-python"); FileManager.default.createFile(atPath: arbitrary.path, contents: Data()); try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: arbitrary.path); let result = try RepositoryConfiguration.validate(root); XCTAssertNotEqual(result.executable, arbitrary) }
    func testBoundedDiagnosticsAndLocalHealth() { XCTAssertEqual(boundedDiagnostic(String(repeating: "x", count: 10), limit: 4).count, 4); XCTAssertFalse(isLocalCoreURL(URL(string: "http://localhost:8765")!)); XCTAssertEqual(URL(string: "http://127.0.0.1:8765")!.appendingPathComponent("health").absoluteString, "http://127.0.0.1:8765/health") }
    func testHealthPolicyRetriesRefusedThenSucceeds() { let p = CoreHealthPolicy(); XCTAssertEqual(p.nextResult(processRunning: true, elapsedMilliseconds: 0, probeHealthy: false), .retry); XCTAssertEqual(p.nextResult(processRunning: true, elapsedMilliseconds: 350, probeHealthy: true), .healthy) }
    func testHealthPolicyProcessExitAndTimeout() { let p = CoreHealthPolicy(); XCTAssertEqual(p.nextResult(processRunning: false, elapsedMilliseconds: 10, probeHealthy: false), .processExited); XCTAssertEqual(p.nextResult(processRunning: true, elapsedMilliseconds: 15_000, probeHealthy: false), .timedOut) }
    func testHealthPolicyBoundsAndLifecycleGates() { let p = CoreHealthPolicy(); XCTAssertGreaterThanOrEqual(p.timeoutMilliseconds, 10_000); XCTAssertGreaterThan(p.retryMilliseconds, 0); let rules = CoreLifecycleRules(); XCTAssertFalse(rules.canStart(ownedProcessExists: true)); XCTAssertTrue(rules.canStop(ownedProcessExists: true)); XCTAssertEqual(rules.stateAfterLaunchFailure(), .unavailable) }
    func testBoundedDiagnosticTailsAndSanitization() { let text = (0..<40).map { "line\($0)\u{001b}[31m" }.joined(separator: "\n"); XCTAssertEqual(boundedDiagnosticTail(text, maxLines: 30).count, 30); XCTAssertFalse(boundedDiagnosticTail("bad\u{0007}line", maxLines: 10)[0].unicodeScalars.contains { $0.value < 0x20 }); XCTAssertLessThanOrEqual(sanitizedDiagnosticLine(String(repeating: "x", count: 500)).count, 240); XCTAssertEqual(boundedDiagnosticTail((0..<20).map { "out\($0)" }.joined(separator: "\n"), maxLines: 10).count, 10) }
    func testLaunchSnapshotCapturesProcessConfiguration() throws { let root = try repository(); let config = try RepositoryConfiguration.validate(root); let process = Process(); process.executableURL = config.executable; process.arguments = ["-m", "uvicorn", "cauco_core.main:app", "--host", "127.0.0.1", "--port", "8765"]; process.currentDirectoryURL = config.repository; let snapshot = CoreLaunchDiagnosticSnapshot(process: process, configuration: CoreLaunchConfiguration(executable: config.executable, repository: config.repository), state: .starting); XCTAssertEqual(snapshot.executable, config.executable); XCTAssertEqual(snapshot.workingDirectory, config.repository); XCTAssertEqual(snapshot.arguments, process.arguments); XCTAssertEqual(snapshot.lifecycleState, .starting) }
}
